### ISSUE TITLE
Previous page (Left to right) flip effect

### ISSUE THREAD

**Issue by M144-Coder** [gsioteam/flip_widget#2]
Thank you for this great library @gsioteam .

How to achieve the same flip effect but from the opposite direction which is from bottom left to the bottom right direction (previous page flip effect).

**Comment by gsioteam** [comment]
Added leftToRight option [a6e88cc](https://github.com/gsioteam/flip_widget/commit/a6e88cc0f2709e830233b2e9d229693d00430d16)

**Comment by M144-Coder** [comment]
Thanks for the solution, I confirm it's working. But I think it will be better to pass the left to right parameter to the startFlip and/or flip function instead of the FlipWidget itself.
